version: '3.8'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - 3306:3306

    discord-bot:
        build: .
        restart: always
        environment:
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_PORT: ${DB_PORT}
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            DISCORD_BOT_PREFIX: ${DISCORD_BOT_PREFIX}
            DISCORD_BOT_APP_ID: ${DISCORD_BOT_APP_ID}
            AUTHOR_ID: ${AUTHOR_ID}
        volumes:
            - ./src:/app/src
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASS}
        ports:
            - 8080:80
        links:
            - db
        depends_on:
            - db